{"error":{"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"::","port":3000},"level":"error","message":"uncaughtException: listen EADDRINUSE: address already in use :::3000\nError: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1290:14)\n    at listenInCluster (net.js:1338:12)\n    at Server.listen (net.js:1425:7)\n    at Function.listen (D:\\NodejS-API\\node_modules\\express\\lib\\application.js:618:24)\n    at Object.<anonymous> (D:\\NodejS-API\\server.js:31:5)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:282:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)","stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1290:14)\n    at listenInCluster (net.js:1338:12)\n    at Server.listen (net.js:1425:7)\n    at Function.listen (D:\\NodejS-API\\node_modules\\express\\lib\\application.js:618:24)\n    at Object.<anonymous> (D:\\NodejS-API\\server.js:31:5)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:282:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)","exception":true,"date":"Sat Dec 29 2018 04:19:26 GMT+0700 (Indochina Time)","process":{"pid":1164,"uid":null,"gid":null,"cwd":"D:\\NodejS-API","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.14.2","argv":["C:\\Program Files\\nodejs\\node.exe","D:\\NodejS-API\\server.js"],"memoryUsage":{"rss":52666368,"heapTotal":39620608,"heapUsed":22903792,"external":128163}},"os":{"loadavg":[0,0,0],"uptime":83027},"trace":[{"column":14,"file":"net.js","function":"Server.setupListenHandle [as _listen2]","line":1290,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"net.js","function":"listenInCluster","line":1338,"method":null,"native":false},{"column":7,"file":"net.js","function":"Server.listen","line":1425,"method":"listen","native":false},{"column":24,"file":"D:\\NodejS-API\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":618,"method":"listen","native":false},{"column":5,"file":"D:\\NodejS-API\\server.js","function":null,"line":31,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":530,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":742,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":282,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":743,"method":null,"native":false}],"timestamp":"2018-12-28T21:19:26.426Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:53:32.489Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:53:32.493Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:53:42.802Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:53:42.803Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:54:20.099Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:54:20.101Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'account.customerNumber' in 'field list'","sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;"},"sql":"SELECT `account`.`accountNumber`, `account`.`openDate`, `account`.`balance`, `account`.`customerNumber`, `account`.`customer_id`, `customer`.`customerNumber` AS `customer.customerNumber`, `customer`.`firstName` AS `customer.firstName`, `customer`.`lastName` AS `customer.lastName`, `customer`.`birthDate` AS `customer.birthDate`, `customer`.`username` AS `customer.username`, `customer`.`password` AS `customer.password`, `customer`.`phoneNumber` AS `customer.phoneNumber`, `customer`.`phoneType` AS `customer.phoneType` FROM `account` AS `account` LEFT OUTER JOIN `customer` AS `customer` ON `account`.`customer_id` = `customer`.`customerNumber`;","level":"error","timestamp":"2018-12-29T03:54:45.580Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'account.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T03:54:45.582Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"3","origin":"DB","instance":{"accountNumber":3,"openDate":"2010-12-12T00:00:00.000Z","balance":"40000","customer_id":3},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"3"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);","level":"error","timestamp":"2018-12-29T03:59:23.041Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T03:59:23.061Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"3","origin":"DB","instance":{"accountNumber":3,"openDate":"2010-12-12T00:00:00.000Z","balance":"40000","customer_id":3},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"3"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (3,'2010-12-12 00:00:00','40000',3);","level":"error","timestamp":"2018-12-29T04:00:13.177Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T04:00:13.179Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"2","origin":"DB","instance":{"accountNumber":2,"openDate":"2018-10-10T00:00:00.000Z","balance":"5000","customer_id":2},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"2"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES (2,'2018-10-10 00:00:00','5000',2);","level":"error","timestamp":"2018-12-29T04:15:24.456Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T04:15:24.461Z"}
{"level":"error","timestamp":"2018-12-29T07:42:31.132Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T07:42:31.134Z"}
{"level":"error","timestamp":"2018-12-29T07:43:07.897Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T07:43:07.897Z"}
{"level":"error","timestamp":"2018-12-29T07:43:07.906Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T07:43:07.906Z"}
{"level":"error","timestamp":"2018-12-29T09:11:48.367Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T09:11:48.367Z"}
{"level":"error","timestamp":"2018-12-29T09:12:27.437Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T09:12:27.439Z"}
{"level":"error","timestamp":"2018-12-29T09:12:27.460Z"}
{"message":"error call getById : ReferenceError: res is not defined","level":"error","timestamp":"2018-12-29T09:12:27.461Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'accountId.customerNumber' in 'field list'","sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customerNumber`, `accountId`.`customer_id`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer_id` = `customerId`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'accountId.customerNumber' in 'field list'","sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customerNumber`, `accountId`.`customer_id`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer_id` = `customerId`.`customerNumber`;"},"sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customerNumber`, `accountId`.`customer_id`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer_id` = `customerId`.`customerNumber`;","level":"error","timestamp":"2018-12-29T10:01:54.126Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'accountId.customerNumber' in 'field list'","level":"error","timestamp":"2018-12-29T10:01:54.127Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'accountId.customer' in 'field list'","sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customer_id` AS `customerNumber`, `accountId`.`customer`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer` = `customerId`.`customerNumber`;"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'accountId.customer' in 'field list'","sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customer_id` AS `customerNumber`, `accountId`.`customer`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer` = `customerId`.`customerNumber`;"},"sql":"SELECT `accountId`.`accountNumber`, `accountId`.`openDate`, `accountId`.`balance`, `accountId`.`customer_id` AS `customerNumber`, `accountId`.`customer`, `customerId`.`customerNumber` AS `customerId.customerNumber`, `customerId`.`firstName` AS `customerId.firstName`, `customerId`.`lastName` AS `customerId.lastName`, `customerId`.`birthDate` AS `customerId.birthDate`, `customerId`.`username` AS `customerId.username`, `customerId`.`password` AS `customerId.password`, `customerId`.`phoneNumber` AS `customerId.phoneNumber`, `customerId`.`phoneType` AS `customerId.phoneType` FROM `account` AS `accountId` LEFT OUTER JOIN `customer` AS `customerId` ON `accountId`.`customer` = `customerId`.`customerNumber`;","level":"error","timestamp":"2018-12-29T10:02:49.104Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'accountId.customer' in 'field list'","level":"error","timestamp":"2018-12-29T10:02:49.106Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"6","origin":"DB","instance":{"idtrans":"6c03cd90-a111-4392-9b00-f50595f64519","amountsign":"c","amount":"266666000","type":"top up"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"6"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');","level":"error","timestamp":"2018-12-29T10:15:47.422Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:15:47.426Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"6","origin":"DB","instance":{"idtrans":"6c03cd90-a111-4392-9b00-f50595f64519","amountsign":"c","amount":"266666000","type":"top up"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"6"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');","level":"error","timestamp":"2018-12-29T10:16:04.027Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:16:04.029Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"6","origin":"DB","instance":{"idtrans":"6c03cd90-a111-4392-9b00-f50595f64519","amountsign":"c","amount":"266666000","type":"top up"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"6"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '6' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('6c03cd90-a111-4392-9b00-f50595f64519','top up','c','266666000');","level":"error","timestamp":"2018-12-29T10:16:31.097Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:16:31.098Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');","fields":["account_id"],"table":"account","index":"FK_account","reltype":"child","level":"error","timestamp":"2018-12-29T10:19:11.430Z"}
{"message":"error while select: SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-29T10:19:11.432Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`) VALUES ('cf3c6ece-1c6b-41de-86e3-404df0ff6501','top up','c','266666000');","fields":["account_id"],"table":"account","index":"FK_account","reltype":"child","level":"error","timestamp":"2018-12-29T10:19:29.350Z"}
{"message":"error while select: SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-29T10:19:29.351Z"}
{"error":{},"level":"error","message":"uncaughtException: Naming collision between attribute 'accountId' and association 'accountId' on model transaction. To remedy this, change either foreignKey or as in your association definition\nError: Naming collision between attribute 'accountId' and association 'accountId' on model transaction. To remedy this, change either foreignKey or as in your association definition\n    at Object.checkNamingCollision (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\helpers.js:7:11)\n    at BelongsTo.injectAttributes (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\belongs-to.js:99:13)\n    at Function.<anonymous> (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\mixin.js:95:17)\n    at Object.<anonymous> (D:\\NodejS-API\\db\\sequelize.js:22:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (D:\\NodejS-API\\dao\\customer-sequelize.js:1:84)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (D:\\NodejS-API\\controller\\customercontroller.js:2:28)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)","stack":"Error: Naming collision between attribute 'accountId' and association 'accountId' on model transaction. To remedy this, change either foreignKey or as in your association definition\n    at Object.checkNamingCollision (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\helpers.js:7:11)\n    at BelongsTo.injectAttributes (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\belongs-to.js:99:13)\n    at Function.<anonymous> (D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\mixin.js:95:17)\n    at Object.<anonymous> (D:\\NodejS-API\\db\\sequelize.js:22:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (D:\\NodejS-API\\dao\\customer-sequelize.js:1:84)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (D:\\NodejS-API\\controller\\customercontroller.js:2:28)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)","exception":true,"date":"Sat Dec 29 2018 17:23:25 GMT+0700 (Indochina Time)","process":{"pid":13344,"uid":null,"gid":null,"cwd":"D:\\NodejS-API","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.14.2","argv":["C:\\Program Files\\nodejs\\node.exe","D:\\NodejS-API\\server.js"],"memoryUsage":{"rss":51638272,"heapTotal":39096320,"heapUsed":22472072,"external":111779}},"os":{"loadavg":[0,0,0],"uptime":130064},"trace":[{"column":11,"file":"D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\helpers.js","function":"Object.checkNamingCollision","line":7,"method":"checkNamingCollision","native":false},{"column":13,"file":"D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\belongs-to.js","function":"BelongsTo.injectAttributes","line":99,"method":"injectAttributes","native":false},{"column":17,"file":"D:\\NodejS-API\\node_modules\\sequelize\\lib\\associations\\mixin.js","function":null,"line":95,"method":null,"native":false},{"column":13,"file":"D:\\NodejS-API\\db\\sequelize.js","function":null,"line":22,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":530,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":637,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":22,"method":null,"native":false},{"column":84,"file":"D:\\NodejS-API\\dao\\customer-sequelize.js","function":null,"line":1,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":530,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":637,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":22,"method":null,"native":false},{"column":28,"file":"D:\\NodejS-API\\controller\\customercontroller.js","function":null,"line":2,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false}],"timestamp":"2018-12-29T10:23:25.660Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);","fields":["account_id"],"table":"account","index":"FK_account","reltype":"child","level":"error","timestamp":"2018-12-29T10:24:23.904Z"}
{"message":"error while select: SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-29T10:24:23.905Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','266666000',10);","fields":["account_id"],"table":"account","index":"FK_account","reltype":"child","level":"error","timestamp":"2018-12-29T10:24:30.665Z"}
{"message":"error while select: SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`transaction`, CONSTRAINT `FK_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`AccountNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-29T10:24:30.665Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"14","origin":"DB","instance":{"idtrans":"14a840e6-5956-43d9-9243-b68c1998b499","type":"top up","amountsign":"c","amount":"3456","accountNumber":1},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"14"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '14' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','3456',1);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '14' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','3456',1);"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('14a840e6-5956-43d9-9243-b68c1998b499','top up','c','3456',1);","level":"error","timestamp":"2018-12-29T10:25:33.684Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:25:33.689Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"9460","origin":"DB","instance":{"idtrans":"9460c068-78dd-4029-b408-0f4f0722afcd","type":"top up","amountsign":"c","amount":"3456","accountNumber":1},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"9460"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '9460' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('9460c068-78dd-4029-b408-0f4f0722afcd','top up','c','3456',1);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '9460' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('9460c068-78dd-4029-b408-0f4f0722afcd','top up','c','3456',1);"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('9460c068-78dd-4029-b408-0f4f0722afcd','top up','c','3456',1);","level":"error","timestamp":"2018-12-29T10:27:31.538Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:27:31.543Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"3196","origin":"DB","instance":{"idtrans":"3196d83e-90f5-4cb5-98f3-06287690ff77","type":"top up","amountsign":"c","amount":"34","accountNumber":1},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"3196"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3196' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('3196d83e-90f5-4cb5-98f3-06287690ff77','top up','c','34',1);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3196' for key 'PRIMARY'","sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('3196d83e-90f5-4cb5-98f3-06287690ff77','top up','c','34',1);"},"sql":"INSERT INTO `transaction` (`idtrans`,`type`,`amountsign`,`amount`,`account_id`) VALUES ('3196d83e-90f5-4cb5-98f3-06287690ff77','top up','c','34',1);","level":"error","timestamp":"2018-12-29T10:28:53.854Z"}
{"message":"error while select: SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-29T10:28:53.859Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '8'"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '8'"},"sql":"DELETE FROM `transaction` WHERE `id` = '8'","level":"error","timestamp":"2018-12-29T10:37:16.639Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'id' in 'where clause'","level":"error","timestamp":"2018-12-29T10:37:16.641Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '14'"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '14'"},"sql":"DELETE FROM `transaction` WHERE `id` = '14'","level":"error","timestamp":"2018-12-29T10:37:20.821Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'id' in 'where clause'","level":"error","timestamp":"2018-12-29T10:37:20.822Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '9'"},"original":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'id' in 'where clause'","sql":"DELETE FROM `transaction` WHERE `id` = '9'"},"sql":"DELETE FROM `transaction` WHERE `id` = '9'","level":"error","timestamp":"2018-12-29T10:37:26.955Z"}
{"message":"error while select: SequelizeDatabaseError: Unknown column 'id' in 'where clause'","level":"error","timestamp":"2018-12-29T10:37:26.956Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','123000','');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','123000','');"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','123000','');","fields":["customer_id"],"table":"customer","index":"FK_customer","reltype":"child","level":"error","timestamp":"2018-12-30T03:56:27.246Z"}
{"message":"error call insert : SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-30T03:56:27.249Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-10 00:00:00','12334','');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-10 00:00:00','12334','');"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-10 00:00:00','12334','');","fields":["customer_id"],"table":"customer","index":"FK_customer","reltype":"child","level":"error","timestamp":"2018-12-30T03:56:53.249Z"}
{"message":"error call insert : SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-30T03:56:53.251Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-25 00:00:00','10001','');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-25 00:00:00','10001','');"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-25 00:00:00','10001','');","fields":["customer_id"],"table":"customer","index":"FK_customer","reltype":"child","level":"error","timestamp":"2018-12-30T03:57:52.930Z"}
{"message":"error call insert : SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-30T03:57:52.932Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-19T00:00:00.000Z","balance":"11111234566","customerNumber":1},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','11111234566',1);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','11111234566',1);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','11111234566',1);","level":"error","timestamp":"2018-12-30T04:00:31.955Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:00:31.995Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-04T00:00:00.000Z","balance":"23456","customerNumber":4},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-04 00:00:00','23456',4);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-04 00:00:00','23456',4);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-04 00:00:00','23456',4);","level":"error","timestamp":"2018-12-30T04:00:50.293Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:00:50.302Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-12T00:00:00.000Z","balance":"12345678","customerNumber":13},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','12345678',13);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','12345678',13);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-12 00:00:00','12345678',13);","level":"error","timestamp":"2018-12-30T04:01:26.481Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:01:26.485Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-19T00:00:00.000Z","balance":"8789698675656467","customerNumber":""},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','8789698675656467','');"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','8789698675656467','');"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','8789698675656467','');","level":"error","timestamp":"2018-12-30T04:01:54.209Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:01:54.210Z"}
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','123456765432','');"},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','123456765432','');"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-19 00:00:00','123456765432','');","fields":["customer_id"],"table":"customer","index":"FK_customer","reltype":"child","level":"error","timestamp":"2018-12-30T04:02:47.146Z"}
{"message":"error call insert : SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`bootcamp`.`account`, CONSTRAINT `FK_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customerNumber`) ON DELETE NO ACTION ON UPDATE NO ACTION)","level":"error","timestamp":"2018-12-30T04:02:47.150Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-21T00:00:00.000Z","balance":"9090909090909090","customerNumber":5},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-21 00:00:00','9090909090909090',5);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-21 00:00:00','9090909090909090',5);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-21 00:00:00','9090909090909090',5);","level":"error","timestamp":"2018-12-30T04:04:16.957Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:04:16.961Z"}
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"735","origin":"DB","instance":{"accountNumber":"735aed81-a034-4410-8613-62ee4258a11d","openDate":"2018-12-20T00:00:00.000Z","balance":"12345","customerNumber":8},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"735"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-20 00:00:00','12345',8);"},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '735' for key 'PRIMARY'","sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-20 00:00:00','12345',8);"},"sql":"INSERT INTO `account` (`accountNumber`,`openDate`,`balance`,`customer_id`) VALUES ('735aed81-a034-4410-8613-62ee4258a11d','2018-12-20 00:00:00','12345',8);","level":"error","timestamp":"2018-12-30T04:06:08.844Z"}
{"message":"error call insert : SequelizeUniqueConstraintError: Validation error","level":"error","timestamp":"2018-12-30T04:06:08.846Z"}
